### ISSUE TITLE
Change color of shapes and background

### ISSUE THREAD

**Issue by jmcginnis29** [WSU-4110/Math_Scriptum#11]
|FR11.  Change color of shapes and background |
|---|
|**Goal**: Application will have options to change the color of the shapes and the background.
**Stakeholders:** Students |
| **Description:** The user will have the option to change the color of the built in shapes and change the color of the background. |
| **Origin:** Based on project proposal and discussion in third meeting.|
| **Version:** 1.0  |  
|**Date:** 09/19/2019  
|  **Priority:** 3 |

**Comment by SultanAdil** [comment]
Done by Abdella.
