### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by jmcginnis29** [WSU-4110/Math_Scriptum#17]
|NFR2.  Security |
|---|
|**Goal**: The application will not need internet to operate.
**Stakeholders:** All |
| **Description:** The application will not need internet so all date saved will be local which prevents online theft of data and ensures data is on the local machine only . |
| **Origin:** Security discussion on third meeting.|
| **Version:** 1.0  |  
|**Date:** 09/19/2019  
|  **Priority:** 1 |

**Comment by Abe33O1** [comment]
Since this application has no security threats other than physical theft, security wouldn't be an issue for this application.
