### ISSUE TITLE
Save all work by user

### ISSUE THREAD

**Issue by jmcginnis29** [WSU-4110/Math_Scriptum#6]
|FR6.  Save all work by user  |
|---|
|**Goal**: The application will allow the user to save all their work.
**Stakeholders:** Students/Professionals|
| **Description:** The application will have a save feature so the user can save any 2D shapes drawn or inserted and notes taken. |
| **Origin:** Based on project proposal and second meeting discussion.|
| **Version:** 1.0  |  
|**Date:** 09/19/2019  
|  **Priority:** 5 |

**Comment by SultanAdil** [comment]
Done and Implemented.

See SultanSprint2 Branch Merge.
