### ISSUE TITLE
Display 2D shape change options as chosen by user

### ISSUE THREAD

**Issue by jmcginnis29** [WSU-4110/Math_Scriptum#8]
|FR8.  Display 2D shape change options as chosen by user |
|---|
|**Goal**: The application will allow the user to change the size of the built in shape.
**Stakeholders:** Students|
| **Description:** The user can change the size of the shape to accommodate the graphical background and notes to be taken . |
| **Origin:** Extra features discussed in class.|
| **Version:** 1.0  |  
|**Date:** 09/19/2019  
|  **Priority:** 2 |

**Comment by SultanAdil** [comment]
Done by Abdella.
