### ISSUE TITLE
Display functions and equations as selected by user

### ISSUE THREAD

**Issue by jmcginnis29** [WSU-4110/Math_Scriptum#9]
|FR9.  Display functions and equations as selected by user  |
|---|
|**Goal**: The application will allow the user to change the program layout based on the topic.
**Stakeholders:** Students|
| **Description:** The application will have an program layout best suited for the user by choice whether its for taking notes or studying . |
| **Origin:** Extra features discussed in second meeting.|
| **Version:** 1.0  |  
|**Date:** 09/19/2019  
|  **Priority:** 1 |

**Comment by SultanAdil** [comment]
This is not feasible in Qt. 

Qt does not allow the replacement of widgets, which is how we planned to do layout changes.

**Comment by SultanAdil** [comment]
Edit to overall objective:

Create a user friendly default layout for the user.
